version: '3.5'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data: